import { db } from '@/db';
import { ads } from '@/db/schema';

async function main() {
    const sampleAds = [
        {
            title: 'Premium Banner Top',
            type: 'banner',
            variant: 'horizontal',
            size: 'large',
            contentUrl: 'https://via.placeholder.com/728x90',
            linkUrl: 'https://example.com/product-1',
            position: 'top',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 342,
            impressions: 5678,
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Summer Sale Banner',
            type: 'banner',
            variant: 'horizontal',
            size: 'medium',
            contentUrl: 'https://via.placeholder.com/468x60',
            linkUrl: null,
            position: 'middle',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 256,
            impressions: 4321,
            createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Featured Banner Bottom',
            type: 'banner',
            variant: 'horizontal',
            size: 'medium',
            contentUrl: 'https://via.placeholder.com/728x90',
            linkUrl: 'https://example.com/product-2',
            position: 'bottom',
            status: 'paused',
            startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 12,
            impressions: 45,
            createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Video Ad Sidebar',
            type: 'video',
            variant: 'square',
            size: 'medium',
            contentUrl: 'https://sample-videos.com/video123.mp4',
            linkUrl: 'https://example.com/product-3',
            position: 'sidebar',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: null,
            clicks: 187,
            impressions: 3456,
            createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Product Demo Video',
            type: 'video',
            variant: 'square',
            size: 'large',
            contentUrl: 'https://sample-videos.com/video456.mp4',
            linkUrl: 'https://example.com/product-4',
            position: 'middle',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 423,
            impressions: 7890,
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Promotional Video Top',
            type: 'video',
            variant: 'square',
            size: 'small',
            contentUrl: 'https://sample-videos.com/video789.mp4',
            linkUrl: null,
            position: 'top',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 298,
            impressions: 5234,
            createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Square Ad Sidebar',
            type: 'square',
            variant: 'square',
            size: 'medium',
            contentUrl: 'https://via.placeholder.com/300x250',
            linkUrl: 'https://example.com/product-5',
            position: 'sidebar',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 156,
            impressions: 2987,
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Square Grid Advertisement',
            type: 'square',
            variant: 'square',
            size: 'medium',
            contentUrl: 'https://via.placeholder.com/300x250',
            linkUrl: 'https://example.com/product-6',
            position: 'grid',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 389,
            impressions: 6543,
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Featured Square Bottom',
            type: 'square',
            variant: 'square',
            size: 'small',
            contentUrl: 'https://via.placeholder.com/250x250',
            linkUrl: 'https://example.com/product-7',
            position: 'bottom',
            status: 'paused',
            startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: null,
            clicks: 8,
            impressions: 67,
            createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Premium Square Grid',
            type: 'square',
            variant: 'square',
            size: 'large',
            contentUrl: 'https://via.placeholder.com/336x280',
            linkUrl: null,
            position: 'grid',
            status: 'active',
            startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            clicks: 467,
            impressions: 8765,
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(ads).values(sampleAds);
    
    console.log('✅ Ads seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});