import { db } from '@/db';
import { articles } from '@/db/schema';

async function main() {
    const sampleArticles = [
        // Tecnologia (4 articles)
        {
            title: 'Nova IA revoluciona mercado de tecnologia brasileiro',
            slug: 'nova-ia-revoluciona-mercado-tecnologia-brasileiro',
            description: 'Startup brasileira lança inteligência artificial que promete transformar o setor de atendimento ao cliente. A tecnologia já está sendo testada por grandes empresas nacionais.',
            content: 'Uma startup brasileira acaba de lançar uma nova solução de inteligência artificial que promete revolucionar o mercado de tecnologia no país. A plataforma, desenvolvida ao longo de dois anos, utiliza algoritmos avançados de processamento de linguagem natural.\n\nSegundo os fundadores, a tecnologia já está sendo testada por cinco grandes empresas brasileiras do setor de telecomunicações e varejo. Os resultados preliminares mostram uma redução de 40% no tempo de atendimento ao cliente.\n\nA solução também incorpora aprendizado de máquina contínuo, permitindo que o sistema se adapte às necessidades específicas de cada empresa. Especialistas do setor consideram o desenvolvimento um marco importante para a tecnologia nacional.\n\nA startup planeja expandir suas operações para outros países da América Latina ainda este ano, com foco inicial no México e Argentina.',
            imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600',
            category: 'Tecnologia',
            source: 'TechNews Brasil',
            author: 'João Silva',
            tags: 'tecnologia, inteligência artificial, startups, inovação',
            status: 'published',
            featured: true,
            views: 4532,
            publishedAt: new Date('2024-12-15T10:30:00Z').toISOString(),
            createdAt: new Date('2024-12-15T09:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-15T10:30:00Z').toISOString(),
        },
        {
            title: 'Apple anuncia novos recursos de privacidade no iOS 18',
            slug: 'apple-anuncia-novos-recursos-privacidade-ios-18',
            description: 'A gigante da tecnologia apresenta atualizações focadas em proteção de dados. Usuários terão mais controle sobre suas informações pessoais.',
            content: 'A Apple anunciou hoje uma série de novos recursos de privacidade que serão incluídos no iOS 18, programado para lançamento no próximo ano. As mudanças representam o maior avanço em proteção de dados desde o lançamento do App Tracking Transparency.\n\nEntre as novidades, destaca-se o novo sistema de criptografia de ponta a ponta para backups no iCloud, que impedirá que até mesmo a Apple tenha acesso aos dados dos usuários. A empresa também introduziu controles mais granulares para permissões de aplicativos.\n\nOutro recurso importante é o Privacy Dashboard, que oferece uma visão completa de como os aplicativos estão usando os dados do usuário. Especialistas em segurança digital elogiaram as medidas, considerando-as um passo importante para a indústria.\n\nA atualização também inclui melhorias no Safari para bloquear rastreadores de forma mais eficaz e um novo modo de navegação privada aprimorado.',
            imageUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=600',
            category: 'Tecnologia',
            source: 'G1',
            author: 'Maria Santos',
            tags: 'apple, ios, privacidade, segurança digital',
            status: 'published',
            featured: false,
            views: 3421,
            publishedAt: new Date('2024-12-18T14:20:00Z').toISOString(),
            createdAt: new Date('2024-12-18T13:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-18T14:20:00Z').toISOString(),
        },
        {
            title: 'Computação quântica chega ao Brasil com primeiro laboratório',
            slug: 'computacao-quantica-chega-brasil-primeiro-laboratorio',
            description: 'Universidade brasileira inaugura laboratório de computação quântica. Projeto conta com investimento de R$ 50 milhões e parceria internacional.',
            content: 'O Brasil deu um importante passo na corrida tecnológica mundial com a inauguração do primeiro laboratório de computação quântica do país. Localizado em São Paulo, o centro de pesquisa conta com investimento inicial de R$ 50 milhões.\n\nO projeto é resultado de uma parceria entre a universidade, governo federal e empresas privadas. O laboratório conta com equipamentos de última geração e uma equipe de 30 pesquisadores especializados.\n\nSegundo o coordenador do projeto, o objetivo é desenvolver aplicações práticas de computação quântica para problemas brasileiros, especialmente nas áreas de logística, agricultura e energia.\n\nO laboratório também funcionará como centro de formação, oferecendo cursos e treinamentos para estudantes e profissionais interessados em aprender sobre essa tecnologia emergente.',
            imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=600',
            category: 'Tecnologia',
            source: 'Estadão',
            author: 'Pedro Costa',
            tags: 'computação quântica, ciência, pesquisa, tecnologia',
            status: 'published',
            featured: true,
            views: 2876,
            publishedAt: new Date('2024-12-10T11:00:00Z').toISOString(),
            createdAt: new Date('2024-12-10T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-10T11:00:00Z').toISOString(),
        },
        {
            title: 'Segurança cibernética: Brasil sofre aumento de 60% em ataques',
            slug: 'seguranca-cibernetica-brasil-aumento-ataques',
            description: 'Relatório aponta crescimento alarmante de ciberataques no país. Empresas brasileiras investem em proteção digital.',
            content: 'Um novo relatório sobre segurança digital revela que o Brasil sofreu um aumento de 60% em ataques cibernéticos nos últimos 12 meses. O levantamento foi realizado por uma empresa especializada em segurança da informação.\n\nOs dados mostram que o setor financeiro foi o mais afetado, seguido por varejo e saúde. Ransomware continua sendo a ameaça mais comum, representando 35% de todos os ataques registrados.\n\nEm resposta a essa tendência, empresas brasileiras aumentaram seus investimentos em segurança cibernética em 45%. O mercado de cibersegurança no país deve movimentar R$ 8 bilhões este ano.\n\nEspecialistas recomendam que empresas implementem autenticação multifator, realizem backups regulares e invistam em treinamento de funcionários para prevenir ataques.',
            imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600',
            category: 'Tecnologia',
            source: 'TechNews Brasil',
            author: null,
            tags: 'segurança, cibersegurança, ataques, proteção de dados',
            status: 'draft',
            featured: false,
            views: 0,
            publishedAt: null,
            createdAt: new Date('2024-12-20T15:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-20T16:30:00Z').toISOString(),
        },
        // Finanças (3 articles)
        {
            title: 'Banco Central anuncia nova taxa de juros em decisão histórica',
            slug: 'banco-central-anuncia-nova-taxa-juros-decisao-historica',
            description: 'Copom decide por redução de 0,5 ponto percentual na Selic. Decisão surpreende mercado e pode impactar economia brasileira.',
            content: 'O Comitê de Política Monetária do Banco Central decidiu reduzir a taxa básica de juros em 0,5 ponto percentual, levando a Selic para 11,25% ao ano. A decisão foi unânime e surpreendeu parte do mercado financeiro.\n\nSegundo o comunicado oficial, a redução foi possível devido à desaceleração da inflação e à melhora nas expectativas econômicas. O BC destacou que a decisão foi tomada considerando o cenário internacional favorável.\n\nEconomistas avaliam que a medida deve estimular o consumo e os investimentos, beneficiando especialmente o setor de construção civil e o varejo. O mercado de ações reagiu positivamente à notícia.\n\nO Banco Central sinalizou que pode haver novas reduções na taxa de juros nas próximas reuniões, caso o cenário de inflação controlada se mantenha.',
            imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=600',
            category: 'Finanças',
            source: 'Globo',
            author: 'Ana Paula Rodrigues',
            tags: 'economia, juros, banco central, selic',
            status: 'published',
            featured: true,
            views: 5123,
            publishedAt: new Date('2024-12-12T16:00:00Z').toISOString(),
            createdAt: new Date('2024-12-12T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-12T16:00:00Z').toISOString(),
        },
        {
            title: 'Dólar fecha em queda após intervenção do Banco Central',
            slug: 'dolar-fecha-queda-apos-intervencao-banco-central',
            description: 'Moeda americana recua 2,3% após ação coordenada. BC injeta US$ 3 bilhões no mercado para conter volatilidade.',
            content: 'O dólar fechou em forte queda de 2,3% nesta quinta-feira, cotado a R$ 4,92, após intervenção do Banco Central no mercado de câmbio. A autoridade monetária injetou US$ 3 bilhões através de leilões de linha.\n\nA medida visou conter a volatilidade cambial observada nas últimas semanas. Analistas do mercado financeiro avaliaram a ação como necessária e oportuna, considerando o cenário externo desafiador.\n\nO movimento também foi influenciado por dados positivos da economia brasileira divulgados pela manhã, incluindo crescimento acima do esperado do PIB industrial. Investidores estrangeiros demonstraram renovado interesse no mercado brasileiro.\n\nEspecialistas projetam que o dólar deve se manter estável nas próximas semanas, com possibilidade de novas quedas caso o cenário internacional permaneça favorável.',
            imageUrl: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&h=600',
            category: 'Finanças',
            source: 'UOL',
            author: 'Carlos Mendes',
            tags: 'câmbio, dólar, banco central, economia',
            status: 'published',
            featured: false,
            views: 3654,
            publishedAt: new Date('2024-12-17T18:30:00Z').toISOString(),
            createdAt: new Date('2024-12-17T17:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-17T18:30:00Z').toISOString(),
        },
        {
            title: 'Mercado de criptomoedas registra alta de 15% na semana',
            slug: 'mercado-criptomoedas-registra-alta-15-semana',
            description: 'Bitcoin ultrapassa marca de US$ 45 mil. Investidores brasileiros ampliam participação no mercado digital.',
            content: 'O mercado de criptomoedas registrou forte alta de 15% nesta semana, com o Bitcoin ultrapassando a marca de US$ 45 mil pela primeira vez em seis meses. A valorização foi impulsionada por expectativas de aprovação de novos ETFs nos Estados Unidos.\n\nNo Brasil, o volume de negociações em exchanges locais aumentou 40% no último mês, indicando maior interesse de investidores nacionais por ativos digitais. Especialistas atribuem o movimento à busca por diversificação de portfólio.\n\nOutras criptomoedas também apresentaram ganhos significativos, com Ethereum subindo 12% e várias altcoins registrando valorizações acima de 20%. O mercado total de criptomoedas ultrapassou a marca de US$ 2 trilhões.\n\nAnalistas alertam, no entanto, para a volatilidade característica desses ativos e recomendam cautela aos investidores, especialmente aqueles sem experiência no mercado cripto.',
            imageUrl: 'https://images.unsplash.com/photo-1622630998477-20aa696ecb05?w=800&h=600',
            category: 'Finanças',
            source: 'Folha',
            author: 'Juliana Alves',
            tags: 'criptomoedas, bitcoin, investimentos, mercado financeiro',
            status: 'published',
            featured: false,
            views: 2987,
            publishedAt: new Date('2024-12-14T12:00:00Z').toISOString(),
            createdAt: new Date('2024-12-14T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-14T12:00:00Z').toISOString(),
        },
        // Ciência (3 articles)
        {
            title: 'Descoberta científica surpreende pesquisadores brasileiros',
            slug: 'descoberta-cientifica-surpreende-pesquisadores-brasileiros',
            description: 'Equipe da USP identifica nova espécie na Amazônia. Descoberta pode revolucionar estudos sobre biodiversidade.',
            content: 'Uma equipe de pesquisadores da Universidade de São Paulo fez uma descoberta surpreendente durante expedição científica na Amazônia. Os cientistas identificaram uma nova espécie de primata que pode ser fundamental para entender a evolução da biodiversidade na região.\n\nA descoberta aconteceu em uma área remota da floresta, ainda pouco explorada pela ciência. A nova espécie apresenta características únicas que a diferenciam de todos os primatas conhecidos até o momento.\n\nSegundo os pesquisadores, o animal está adaptado a um habitat específico e pode estar ameaçado devido ao desmatamento. A descoberta reforça a importância da preservação da Amazônia e do investimento em pesquisa científica.\n\nO estudo completo será publicado em uma revista científica internacional nas próximas semanas. A equipe já planeja novas expedições para estudar melhor a espécie e seu habitat.',
            imageUrl: 'https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800&h=600',
            category: 'Ciência',
            source: 'G1',
            author: 'Roberto Oliveira',
            tags: 'ciência, amazônia, biodiversidade, descoberta',
            status: 'published',
            featured: true,
            views: 4231,
            publishedAt: new Date('2024-12-11T09:00:00Z').toISOString(),
            createdAt: new Date('2024-12-11T07:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-11T09:00:00Z').toISOString(),
        },
        {
            title: 'Vacina brasileira contra dengue mostra resultados promissores',
            slug: 'vacina-brasileira-dengue-mostra-resultados-promissores',
            description: 'Testes clínicos indicam eficácia de 85% na prevenção. Instituto Butantan prevê início da distribuição em 2025.',
            content: 'Os resultados da terceira fase de testes da vacina brasileira contra dengue superaram as expectativas dos pesquisadores. O imunizante desenvolvido pelo Instituto Butantan apresentou eficácia de 85% na prevenção da doença.\n\nOs testes envolveram 15 mil voluntários em diferentes regiões do Brasil, áreas endêmicas para dengue. A vacina demonstrou ser segura e eficaz contra os quatro sorotipos do vírus, um avanço significativo no combate à doença.\n\nO instituto planeja submeter o pedido de registro à Anvisa nas próximas semanas. Se aprovada, a distribuição pode começar no primeiro semestre de 2025, inicialmente pelo Sistema Único de Saúde.\n\nEspecialistas consideram o desenvolvimento um marco importante para a saúde pública brasileira, especialmente considerando o aumento de casos de dengue nos últimos anos.',
            imageUrl: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&h=600',
            category: 'Ciência',
            source: 'Estadão',
            author: 'Fernanda Lima',
            tags: 'saúde, vacina, dengue, ciência',
            status: 'published',
            featured: false,
            views: 3876,
            publishedAt: new Date('2024-12-16T11:30:00Z').toISOString(),
            createdAt: new Date('2024-12-16T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-16T11:30:00Z').toISOString(),
        },
        {
            title: 'Observatório brasileiro detecta fenômeno astronômico raro',
            slug: 'observatorio-brasileiro-detecta-fenomeno-astronomico-raro',
            description: 'Astrônomos registram explosão estelar a milhões de anos-luz. Evento pode ajudar a entender evolução do universo.',
            content: 'Astrônomos brasileiros do Observatório Nacional detectaram um fenômeno astronômico extremamente raro: uma supernova tipo Ia em um sistema binário de estrelas. O evento foi observado a aproximadamente 50 milhões de anos-luz da Terra.\n\nA descoberta foi possível graças aos telescópios de última geração instalados no observatório e à colaboração internacional com centros de pesquisa. Os cientistas acompanharam o fenômeno por várias noites consecutivas.\n\nSegundo os pesquisadores, esse tipo de supernova é fundamental para entender a expansão do universo e a natureza da energia escura. Os dados coletados serão compartilhados com a comunidade científica internacional.\n\nA equipe brasileira ganhou reconhecimento internacional pela descoberta, que foi destaque em publicações científicas especializadas.',
            imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&h=600',
            category: 'Ciência',
            source: 'TechNews Brasil',
            author: null,
            tags: 'astronomia, ciência, espaço, descoberta',
            status: 'draft',
            featured: false,
            views: 0,
            publishedAt: null,
            createdAt: new Date('2024-12-19T14:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-19T15:30:00Z').toISOString(),
        },
        // Esportes (3 articles)
        {
            title: 'Brasil vence Argentina e conquista Copa América pela nona vez',
            slug: 'brasil-vence-argentina-conquista-copa-america-nona-vez',
            description: 'Seleção brasileira supera rival em final emocionante. Neymar marca dois gols e lidera time à vitória.',
            content: 'A Seleção Brasileira conquistou sua nona Copa América ao vencer a Argentina por 3 a 1 em uma final emocionante realizada no Maracanã. Neymar foi o grande destaque da partida, marcando dois gols e dando uma assistência.\n\nO jogo começou equilibrado, com as duas equipes criando chances de gol. O Brasil abriu o placar aos 25 minutos do primeiro tempo, com um gol de Neymar após jogada ensaiada em cobrança de falta.\n\nNo segundo tempo, a Argentina empatou, mas o Brasil reagiu rapidamente. Neymar marcou novamente e Vinícius Júnior fechou o placar aos 40 minutos. A torcida brasileira celebrou intensamente a conquista.\n\nO técnico Tite elogiou a dedicação dos jogadores e destacou a importância do título para o futebol brasileiro. Esta é a primeira Copa América conquistada pela seleção desde 2019.',
            imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&h=600',
            category: 'Esportes',
            source: 'Globo',
            author: 'Marcos Silva',
            tags: 'futebol, copa américa, seleção brasileira, neymar',
            status: 'published',
            featured: true,
            views: 4892,
            publishedAt: new Date('2024-12-13T22:00:00Z').toISOString(),
            createdAt: new Date('2024-12-13T20:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-13T22:00:00Z').toISOString(),
        },
        {
            title: 'Flamengo contrata reforço europeu por valor recorde',
            slug: 'flamengo-contrata-reforco-europeu-valor-recorde',
            description: 'Clube carioca anuncia chegada de meio-campista argentino. Transferência custou 25 milhões de euros.',
            content: 'O Flamengo anunciou nesta terça-feira a contratação do meio-campista argentino Matías Fernández, vindo do futebol europeu. A transferência custou 25 milhões de euros, valor recorde para o clube carioca.\n\nO jogador de 27 anos assinou contrato de quatro anos e já está à disposição do técnico para os próximos jogos. Fernández é conhecido por sua habilidade técnica e capacidade de criar jogadas ofensivas.\n\nA diretoria do Flamengo vê a contratação como fundamental para buscar títulos nesta temporada. O clube disputa o Campeonato Brasileiro, Copa do Brasil e Libertadores.\n\nA torcida rubro-negra recebeu a notícia com entusiasmo e já comparou o novo reforço a grandes ídolos que vestiram a camisa do clube no passado.',
            imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=600',
            category: 'Esportes',
            source: 'UOL',
            author: 'Lucas Ferreira',
            tags: 'futebol, flamengo, transferências, campeonato brasileiro',
            status: 'published',
            featured: false,
            views: 3214,
            publishedAt: new Date('2024-12-19T15:00:00Z').toISOString(),
            createdAt: new Date('2024-12-19T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-19T15:00:00Z').toISOString(),
        },
        {
            title: 'Atleta brasileiro bate recorde mundial em maratona',
            slug: 'atleta-brasileiro-bate-recorde-mundial-maratona',
            description: 'Corredor paulista conquista marca histórica em prova internacional. Tempo de 2h01min surpreende especialistas.',
            content: 'O atleta brasileiro Daniel Nascimento entrou para a história do atletismo mundial ao bater o recorde da maratona com um tempo de 2h01min15s. A marca foi conquistada na Maratona de Berlim, uma das provas mais prestigiadas do mundo.\n\nO corredor paulista de 28 anos superou o recorde anterior por 18 segundos, em uma prova que contou com condições climáticas favoráveis. Nascimento manteve ritmo constante durante toda a corrida.\n\nTreinado por um time de especialistas brasileiros, o atleta vinha se preparando há dois anos especificamente para esta prova. A conquista representa um marco histórico para o atletismo brasileiro.\n\nA Confederação Brasileira de Atletismo celebrou o feito e anunciou investimentos para desenvolver novos talentos no esporte.',
            imageUrl: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600',
            category: 'Esportes',
            source: 'Folha',
            author: 'Patrícia Gomes',
            tags: 'atletismo, maratona, recorde, esportes',
            status: 'draft',
            featured: false,
            views: 0,
            publishedAt: null,
            createdAt: new Date('2024-12-21T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-21T11:30:00Z').toISOString(),
        },
        // Entretenimento (3 articles)
        {
            title: 'Série brasileira vence Emmy Internacional pela primeira vez',
            slug: 'serie-brasileira-vence-emmy-internacional-primeira-vez',
            description: 'Produção nacional conquista prêmio em Los Angeles. Atores e diretor celebram reconhecimento histórico.',
            content: 'A série brasileira "Sob o Sol do Sertão" fez história ao vencer o Emmy Internacional na categoria Melhor Drama. É a primeira vez que uma produção nacional conquista o prêmio mais prestigiado da televisão mundial.\n\nA cerimônia aconteceu em Los Angeles e contou com a presença do elenco principal e do diretor. A série, que retrata a vida no interior do Brasil, emocionou jurados e público com sua narrativa autêntica.\n\nO diretor dedicou o prêmio a todos os profissionais brasileiros de audiovisual e destacou a importância do investimento em produções nacionais. O elenco não conteve as lágrimas durante o discurso de agradecimento.\n\nA vitória representa um marco para o audiovisual brasileiro e abre portas para futuras produções nacionais no mercado internacional.',
            imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=600',
            category: 'Entretenimento',
            source: 'G1',
            author: 'Camila Souza',
            tags: 'entretenimento, emmy, séries, televisão',
            status: 'published',
            featured: false,
            views: 3567,
            publishedAt: new Date('2024-12-09T20:00:00Z').toISOString(),
            createdAt: new Date('2024-12-09T18:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-09T20:00:00Z').toISOString(),
        },
        {
            title: 'Festival de cinema brasileiro bate recorde de público',
            slug: 'festival-cinema-brasileiro-bate-recorde-publico',
            description: 'Evento em São Paulo recebe 200 mil visitantes. Filmes nacionais dominam bilheteria e crítica especializada.',
            content: 'O Festival Internacional de Cinema de São Paulo encerrou sua 47ª edição com números recordes. Mais de 200 mil pessoas visitaram as salas de cinema durante os dez dias de evento, superando todas as edições anteriores.\n\nAs produções brasileiras foram destaque, representando 40% dos filmes exibidos. Críticos especializados elogiaram a qualidade técnica e narrativa das obras nacionais apresentadas.\n\nO filme "Caminhos do Interior" levou o prêmio de melhor longa-metragem, além de prêmios técnicos em fotografia e trilha sonora. O diretor agradeceu o apoio do público brasileiro ao cinema nacional.\n\nOrganizadores já confirmaram a realização da próxima edição e prometem ampliar ainda mais a programação e o número de salas participantes.',
            imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&h=600',
            category: 'Entretenimento',
            source: 'Estadão',
            author: 'Ricardo Martins',
            tags: 'cinema, festival, entretenimento, cultura',
            status: 'published',
            featured: false,
            views: 2145,
            publishedAt: new Date('2024-12-08T19:00:00Z').toISOString(),
            createdAt: new Date('2024-12-08T17:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-08T19:00:00Z').toISOString(),
        },
        {
            title: 'Cantora brasileira faz show histórico no Madison Square Garden',
            slug: 'cantora-brasileira-show-historico-madison-square-garden',
            description: 'Anitta lota arena icônica de Nova York. Show marca expansão da música brasileira no mercado americano.',
            content: 'A cantora brasileira Anitta fez história ao lotar o Madison Square Garden, uma das arenas mais icônicas de Nova York. O show reuniu 20 mil pessoas e marcou a consolidação da artista no mercado internacional.\n\nO espetáculo de duas horas e meia apresentou sucessos em português, espanhol e inglês, mostrando a versatilidade da artista. O público cantou junto em todos os idiomas, demonstrando o alcance global da música brasileira.\n\nArtistas internacionais compareceram ao evento e elogiaram a performance. A apresentação contou com cenografia elaborada, efeitos especiais e uma banda de 15 músicos.\n\nA conquista representa um marco importante para a música pop brasileira no exterior e abre caminho para outros artistas nacionais.',
            imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=600',
            category: 'Entretenimento',
            source: 'UOL',
            author: null,
            tags: 'música, anitta, show, entretenimento',
            status: 'draft',
            featured: false,
            views: 0,
            publishedAt: null,
            createdAt: new Date('2024-12-20T16:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-20T17:30:00Z').toISOString(),
        },
        // Saúde (2 articles)
        {
            title: 'Ministério da Saúde lança campanha nacional de vacinação',
            slug: 'ministerio-saude-lanca-campanha-nacional-vacinacao',
            description: 'Nova campanha visa imunizar 80 milhões de brasileiros. Foco em crianças e idosos contra doenças sazonais.',
            content: 'O Ministério da Saúde lançou nesta segunda-feira uma campanha nacional de vacinação que pretende imunizar 80 milhões de brasileiros contra doenças sazonais. O público-alvo principal são crianças e idosos.\n\nA campanha oferece vacinas contra gripe, sarampo e outras doenças que apresentam maior incidência durante o período. Postos de saúde em todo o país estão preparados para atender a população.\n\nSegundo o ministro da Saúde, a meta é alcançar 95% de cobertura vacinal nos grupos prioritários. A pasta investiu R$ 500 milhões na compra de imunizantes e na estruturação da campanha.\n\nEspecialistas recomendam que a população busque a vacinação o quanto antes, especialmente considerando a chegada do período de maior circulação de vírus respiratórios.',
            imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=600',
            category: 'Saúde',
            source: 'Globo',
            author: 'Marina Costa',
            tags: 'saúde, vacinação, saúde pública, ministério',
            status: 'published',
            featured: false,
            views: 2876,
            publishedAt: new Date('2024-12-07T10:00:00Z').toISOString(),
            createdAt: new Date('2024-12-07T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-07T10:00:00Z').toISOString(),
        },
        {
            title: 'Estudo revela benefícios da dieta mediterrânea para brasileiros',
            slug: 'estudo-revela-beneficios-dieta-mediterranea-brasileiros',
            description: 'Pesquisa da Unifesp mostra redução de 30% em doenças cardíacas. Adaptação inclui ingredientes típicos brasileiros.',
            content: 'Um estudo conduzido pela Unifesp revelou que a dieta mediterrânea adaptada à realidade brasileira pode reduzir em até 30% o risco de doenças cardiovasculares. A pesquisa acompanhou 5 mil pessoas durante três anos.\n\nOs pesquisadores desenvolveram uma versão da dieta que substitui ingredientes europeus por opções brasileiras similares, mantendo os benefícios nutricionais. A adaptação torna o regime alimentar mais acessível e sustentável.\n\nOs resultados mostraram melhorias significativas em marcadores de saúde, incluindo redução do colesterol e da pressão arterial. Participantes também relataram mais disposição no dia a dia.\n\nNutricionistas recomendam a adoção gradual da dieta, com acompanhamento profissional para garantir equilíbrio nutricional adequado às necessidades individuais.',
            imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600',
            category: 'Saúde',
            source: 'Folha',
            author: 'Beatriz Santos',
            tags: 'saúde, nutrição, dieta, bem-estar',
            status: 'published',
            featured: false,
            views: 1987,
            publishedAt: new Date('2024-12-06T14:00:00Z').toISOString(),
            createdAt: new Date('2024-12-06T12:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-06T14:00:00Z').toISOString(),
        },
        // Negócios (2 articles)
        {
            title: 'Startup brasileira recebe investimento de US$ 100 milhões',
            slug: 'startup-brasileira-recebe-investimento-100-milhoes',
            description: 'Empresa de tecnologia financeira atrai investidores internacionais. Rodada de investimento série C bate recorde nacional.',
            content: 'A startup brasileira FinTech Solutions anunciou o fechamento de uma rodada de investimento série C no valor de US$ 100 milhões, liderada por fundos internacionais. É o maior investimento do setor no Brasil em 2024.\n\nA empresa, que desenvolve soluções de pagamento digital, planeja usar os recursos para expandir operações na América Latina e investir em novas tecnologias. A startup já opera em cinco países.\n\nSegundo os fundadores, o investimento reflete a confiança do mercado no potencial da empresa e na qualidade das soluções oferecidas. A empresa emprega atualmente 500 pessoas.\n\nO ecossistema de startups brasileiro celebrou o anúncio, vendo-o como sinal de maturidade do setor e da capacidade de empresas nacionais de atrair capital internacional.',
            imageUrl: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=600',
            category: 'Negócios',
            source: 'TechNews Brasil',
            author: 'Alexandre Pereira',
            tags: 'negócios, startups, investimentos, fintech',
            status: 'published',
            featured: false,
            views: 2543,
            publishedAt: new Date('2024-12-05T11:00:00Z').toISOString(),
            createdAt: new Date('2024-12-05T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-05T11:00:00Z').toISOString(),
        },
        {
            title: 'E-commerce brasileiro cresce 25% e supera expectativas',
            slug: 'ecommerce-brasileiro-cresce-25-supera-expectativas',
            description: 'Vendas online movimentam R$ 150 bilhões no ano. Black Friday e Natal impulsionam resultados históricos.',
            content: 'O comércio eletrônico brasileiro registrou crescimento de 25% em 2024, movimentando R$ 150 bilhões e superando todas as expectativas do setor. Os dados foram divulgados pela Associação Brasileira de Comércio Eletrônico.\n\nA Black Friday e o período natalino foram responsáveis por 35% do faturamento total do ano. Categorias como eletrônicos, moda e produtos de beleza lideraram as vendas.\n\nEspecialistas atribuem o crescimento à maior confiança do consumidor e à melhora nos serviços de logística. O número de empresas que iniciaram operações online aumentou 40% no período.\n\nA expectativa para 2025 é de crescimento ainda maior, impulsionado por novas tecnologias e pela expansão do acesso à internet em regiões antes pouco atendidas.',
            imageUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&h=600',
            category: 'Negócios',
            source: 'Estadão',
            author: 'Rodrigo Almeida',
            tags: 'negócios, e-commerce, vendas, varejo',
            status: 'draft',
            featured: false,
            views: 0,
            publishedAt: null,
            createdAt: new Date('2024-12-22T13:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-22T14:30:00Z').toISOString(),
        },
    ];

    await db.insert(articles).values(sampleArticles);
    
    console.log('✅ Articles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});