import { db } from '@/db';
import { videos } from '@/db/schema';

async function main() {
    const sampleVideos = [
        {
            title: 'Brasil anuncia nova parceria econômica com União Europeia',
            description: 'Governo brasileiro firma acordo histórico de cooperação comercial com a União Europeia. O acordo prevê facilidades para importação e exportação de produtos tecnológicos e agrícolas, fortalecendo as relações bilaterais entre as regiões.',
            youtubeUrl: 'https://www.youtube.com/watch?v=X9DJzmMwJ0o',
            thumbnailUrl: 'https://i.ytimg.com/vi/X9DJzmMwJ0o/maxresdefault.jpg',
            category: 'Internacional',
            duration: '8:45',
            views: 15420,
            likes: 892,
            source: 'IspiAI Notícias',
            publishedAt: new Date('2024-12-15').toISOString(),
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            title: 'Mercado financeiro reage positivamente às novas medidas econômicas',
            description: 'Bolsa de valores registra alta de 3,2% após anúncio de medidas para controle da inflação. Especialistas avaliam que as novas políticas econômicas podem trazer estabilidade e crescimento sustentável para o país nos próximos trimestres.',
            youtubeUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
            thumbnailUrl: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg',
            category: 'Economia',
            duration: '12:30',
            views: 28340,
            likes: 1456,
            source: 'Globo News',
            publishedAt: new Date('2024-12-18').toISOString(),
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            title: 'Amazônia registra menor taxa de desmatamento em 15 anos',
            description: 'Dados do INPE mostram redução histórica no desmatamento da floresta amazônica. As políticas de preservação ambiental e o uso de tecnologia de monitoramento por satélite têm sido fundamentais para alcançar esses resultados positivos.',
            youtubeUrl: 'https://www.youtube.com/watch?v=yWWW8JEqW3c',
            thumbnailUrl: 'https://i.ytimg.com/vi/yWWW8JEqW3c/maxresdefault.jpg',
            category: 'Sustentabilidade',
            duration: '10:15',
            views: 45230,
            likes: 1987,
            source: 'CNN Brasil',
            publishedAt: new Date('2024-12-10').toISOString(),
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            title: 'Festival de Cinema Brasileiro bate recorde de público',
            description: 'A 48ª edição do Festival de Cinema de Gramado recebeu mais de 120 mil visitantes. Produções nacionais ganharam destaque internacional, mostrando a força e diversidade do cinema brasileiro contemporâneo.',
            youtubeUrl: 'https://www.youtube.com/watch?v=Lrj2Hq7xqQ8',
            thumbnailUrl: 'https://i.ytimg.com/vi/Lrj2Hq7xqQ8/maxresdefault.jpg',
            category: 'Entretenimento',
            duration: '15:20',
            views: 32150,
            likes: 1678,
            source: 'UOL',
            publishedAt: new Date('2024-12-12').toISOString(),
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            title: 'Copa do Mundo 2026: Brasil garante vaga com vitória histórica',
            description: 'Seleção brasileira vence Argentina por 3 a 1 e confirma classificação antecipada para a Copa do Mundo de 2026. A atuação da equipe demonstrou evolução tática e técnica, renovando as esperanças dos torcedores brasileiros.',
            youtubeUrl: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
            thumbnailUrl: 'https://i.ytimg.com/vi/9bZkp7q19f0/maxresdefault.jpg',
            category: 'Brasil',
            duration: '18:45',
            views: 52890,
            likes: 2345,
            source: 'G1',
            publishedAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            title: 'Infraestrutura: Governo anuncia investimento em rodovias',
            description: 'Plano prevê investimento de R$ 150 bilhões em infraestrutura rodoviária nos próximos cinco anos. O projeto inclui duplicação de estradas federais e manutenção de rodovias estratégicas para o escoamento da produção agrícola.',
            youtubeUrl: 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
            thumbnailUrl: 'https://i.ytimg.com/vi/TcMBFSGVi1c/maxresdefault.jpg',
            category: 'Brasil',
            duration: '9:30',
            views: 18765,
            likes: 945,
            source: 'IspiAI Notícias',
            publishedAt: new Date('2024-12-08').toISOString(),
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            title: 'Museu Nacional reabre após restauração histórica',
            description: 'Após cinco anos de trabalho intenso, o Museu Nacional do Rio de Janeiro reabre suas portas ao público. A restauração preservou a memória histórica e científica brasileira, incorporando tecnologias modernas de preservação e segurança.',
            youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            thumbnailUrl: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
            category: 'Cultura',
            duration: '14:22',
            views: 38540,
            likes: 1823,
            source: 'Globo News',
            publishedAt: new Date('2024-12-05').toISOString(),
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            title: 'Congresso Nacional debate reforma tributária',
            description: 'Deputados e senadores realizam audiência pública para discutir os pontos principais da reforma tributária. A proposta busca simplificar o sistema de impostos brasileiro e reduzir a burocracia para empresas e cidadãos.',
            youtubeUrl: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
            thumbnailUrl: 'https://i.ytimg.com/vi/JGwWNGJdvx8/maxresdefault.jpg',
            category: 'Política',
            duration: '22:10',
            views: 25670,
            likes: 1234,
            source: 'CNN Brasil',
            publishedAt: new Date('2024-12-17').toISOString(),
            createdAt: new Date('2024-12-17').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        {
            title: 'E-sports brasileiro conquista título mundial de CS2',
            description: 'Equipe brasileira FURIA vence campeonato mundial de Counter-Strike 2 em partida épica. A vitória marca um momento histórico para os e-sports nacionais e comprova o talento dos jogadores brasileiros no cenário competitivo internacional.',
            youtubeUrl: 'https://www.youtube.com/watch?v=hTWKbfoikeg',
            thumbnailUrl: 'https://i.ytimg.com/vi/hTWKbfoikeg/maxresdefault.jpg',
            category: 'Games',
            duration: '16:55',
            views: 67890,
            likes: 3456,
            source: 'UOL',
            publishedAt: new Date('2024-12-22').toISOString(),
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            title: 'Inteligência Artificial revoluciona educação brasileira',
            description: 'Escolas públicas implementam ferramentas de IA para personalizar o ensino. O projeto piloto mostra resultados promissores no engajamento dos alunos e na melhoria do desempenho acadêmico, especialmente em matemática e ciências.',
            youtubeUrl: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
            thumbnailUrl: 'https://i.ytimg.com/vi/M7lc1UVf-VE/maxresdefault.jpg',
            category: 'Educação',
            duration: '11:40',
            views: 34210,
            likes: 1567,
            source: 'G1',
            publishedAt: new Date('2024-12-14').toISOString(),
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-14').toISOString(),
        },
        {
            title: 'SUS lança programa de telemedicina em todo o país',
            description: 'Ministério da Saúde anuncia expansão de serviços de telemedicina para atender regiões remotas do Brasil. A iniciativa permitirá consultas especializadas por videoconferência, reduzindo filas e melhorando o acesso à saúde de qualidade.',
            youtubeUrl: 'https://www.youtube.com/watch?v=pXRviuL6vMY',
            thumbnailUrl: 'https://i.ytimg.com/vi/pXRviuL6vMY/maxresdefault.jpg',
            category: 'Saúde',
            duration: '13:25',
            views: 41230,
            likes: 1890,
            source: 'IspiAI Notícias',
            publishedAt: new Date('2024-12-11').toISOString(),
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            title: 'Startup brasileira desenvolve energia solar mais eficiente',
            description: 'Empresa nacional cria tecnologia inovadora que aumenta em 40% a eficiência de painéis solares. A descoberta pode revolucionar o mercado de energia renovável no Brasil e contribuir significativamente para a matriz energética limpa do país.',
            youtubeUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
            thumbnailUrl: 'https://i.ytimg.com/vi/fJ9rUzIMcZQ/maxresdefault.jpg',
            category: 'Sustentabilidade',
            duration: '10:50',
            views: 29560,
            likes: 1432,
            source: 'CNN Brasil',
            publishedAt: new Date('2024-12-19').toISOString(),
            createdAt: new Date('2024-12-19').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        }
    ];

    await db.insert(videos).values(sampleVideos);
    
    console.log('✅ Videos seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});